# Generated by Django 5.2.16 on 2026-07-30 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='user agent')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'download log',
                'verbose_name_plural': 'download logs',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='order number')),
                ('total_amount', models.IntegerField(verbose_name='total amount')),
                ('fee_amount', models.IntegerField(default=0, verbose_name='fee')),
                ('shipping_amount', models.IntegerField(default=0, verbose_name='shipping')),
                ('status', models.CharField(choices=[('pending', '入金待ち'), ('paid', '入金確認済'), ('shipped', '発送済'), ('completed', '完了'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='status')),
                ('payment_method', models.CharField(choices=[('bank_transfer', '銀行振込'), ('convenience', 'コンビニ支払い'), ('paypay', 'PayPay送金')], max_length=20, verbose_name='payment method')),
                ('shipping_name', models.CharField(blank=True, default='', max_length=100, verbose_name='shipping name')),
                ('shipping_zip', models.CharField(blank=True, default='', max_length=8, verbose_name='zip code')),
                ('shipping_address', models.CharField(blank=True, default='', max_length=255, verbose_name='address')),
                ('shipping_phone', models.CharField(blank=True, default='', max_length=15, verbose_name='phone')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='shipped at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='product name')),
                ('product_price', models.IntegerField(verbose_name='price at order')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('subtotal', models.IntegerField(verbose_name='subtotal')),
                ('is_downloadable', models.BooleanField(default=False, verbose_name='downloadable')),
                ('download_count', models.IntegerField(default=0, verbose_name='download count')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='last downloaded')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('bank_transfer', '銀行振込'), ('convenience', 'コンビニ支払い'), ('paypay', 'PayPay送金')], max_length=20, verbose_name='payment method')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('status', models.CharField(choices=[('pending', '入金待ち'), ('confirmed', '入金確認済'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='status')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('processing', '処理中'), ('completed', '完了'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='status')),
                ('bank_info', models.TextField(help_text='申請時点の振込先情報スナップショット', verbose_name='bank info')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'withdrawal',
                'verbose_name_plural': 'withdrawals',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
            ],
            options={
                'verbose_name': 'cart item',
                'verbose_name_plural': 'cart items',
            },
        ),
    ]
