# Generated by Django 5.2.16 on 2026-07-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_order_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='paypal order id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', '銀行振込'), ('convenience', 'コンビニ支払い'), ('paypay', 'PayPay送金'), ('stripe', 'クレジットカード (Stripe)'), ('paypal', 'PayPal')], max_length=20, verbose_name='payment method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', '銀行振込'), ('convenience', 'コンビニ支払い'), ('paypay', 'PayPay送金'), ('stripe', 'クレジットカード (Stripe)'), ('paypal', 'PayPal')], max_length=20, verbose_name='payment method'),
        ),
    ]
